log:
  level: debug
  format: json
  leak_sensitive_values: true

serve:
  read:
    host: 0.0.0.0
    port: 4466
  write:
    host: 0.0.0.0
    port: 4467

dsn: memory

namespaces: 
  - id: 0
    name: document
  - id: 1
    name: role